// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Recipe generation flow that takes identified ingredients and time constraints to generate a recipe.
 *
 * - generateRecipe - A function that handles the recipe generation process.
 * - GenerateRecipeInput - The input type for the generateRecipe function.
 * - GenerateRecipeOutput - The return type for the generateRecipe function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipeInputSchema = z.object({
  ingredients: z.array(
    z.string().describe('A list of identified ingredients.')
  ).describe('The ingredients available for the recipe.'),
  quantity: z.record(z.number()).describe('The quantity of each ingredient'),
  cookingTime: z.number().optional().describe('The maximum cooking time in minutes.'),
  bakingTime: z.number().optional().describe('The maximum baking time in minutes.'),
});
export type GenerateRecipeInput = z.infer<typeof GenerateRecipeInputSchema>;

const GenerateRecipeOutputSchema = z.object({
  recipeName: z.string().describe('The name of the generated recipe.'),
  ingredients: z.array(z.string()).describe('The list of ingredients with quantities required for the recipe.'),
  instructions: z.string().describe('The cooking instructions for the recipe.'),
  cookingTime: z.number().describe('The estimated cooking time in minutes.'),
  bakingTime: z.number().describe('The estimated baking time in minutes.'),
});
export type GenerateRecipeOutput = z.infer<typeof GenerateRecipeOutputSchema>;

export async function generateRecipe(input: GenerateRecipeInput): Promise<GenerateRecipeOutput> {
  return generateRecipeFlow(input);
}

const generateRecipePrompt = ai.definePrompt({
  name: 'generateRecipePrompt',
  input: {schema: GenerateRecipeInputSchema},
  output: {schema: GenerateRecipeOutputSchema},
  prompt: `You are a world-class chef specializing in creating recipes based on provided ingredients and time constraints.

  Based on the following ingredients and constraints, generate a delicious and feasible recipe.

  Ingredients: {{ingredients}}
  Quantities: {{quantity}}
  {{#if cookingTime}}Maximum Cooking Time: {{cookingTime}} minutes{{/if}}
  {{#if bakingTime}}Maximum Baking Time: {{bakingTime}} minutes{{/if}}

  Ensure the recipe includes:
  - A creative and appealing recipe name.
  - A detailed list of ingredients with specific quantities.
  - Step-by-step cooking instructions.
  - Estimated cooking time in minutes.
  - Estimated baking time in minutes.
  `,
});

const generateRecipeFlow = ai.defineFlow(
  {
    name: 'generateRecipeFlow',
    inputSchema: GenerateRecipeInputSchema,
    outputSchema: GenerateRecipeOutputSchema,
  },
  async input => {
    const {output} = await generateRecipePrompt(input);
    return output!;
  }
);
